### ISSUE TITLE
Incorrect displaying of combo points for rogue and feral druid

### ISSUE THREAD

**Issue by cbb356** [Haleth/FreeUI#104]
Version of WOW: 7.0.3 (22267) 64-bit PTR and live
Version of FreeUI: 9.0.0
Description: CP for rogue and feral druid characters are displayed incorrect. Receiving and spending CP aren't displayed on current target. When target is changed CP, numbers is correct (2nd attach file). But on second target  CP quantity don't change again.
See attached files
![wowscrnshot_072016_122036](https://cloud.githubusercontent.com/assets/12935967/16982999/77a63898-4e7b-11e6-8c41-21ecba8282da.jpg)
![wowscrnshot_072016_130012](https://cloud.githubusercontent.com/assets/12935967/16983030/95ecc164-4e7b-11e6-8a31-ba0e91be9069.jpg)
![wowscrnshot_072016_130108](https://cloud.githubusercontent.com/assets/12935967/16983031/95ee4caa-4e7b-11e6-87b2-377f341c5ef1.jpg)

**Comment by camsu** [comment]
This fixed it for me, go in the FreeUI folder in ur addons, then ścripts > combo, and change the LUA text at the bottom to this: 

combo:RegisterEvent("PLAYER_TARGET_CHANGED")
combo:RegisterEvent("UNIT_POWER")
combo:RegisterEvent("UNIT_EXITED_VEHICLE")
combo:SetScript("OnEvent", function(self, event, unit)
    if event == "PLAYER_TARGET_CHANGED" then
        UpdatePoints()
    elseif event == "UNIT_POWER" then
        if unit == "player" or unit == "vehicle" then
            UpdatePoints()
        end
    elseif event == "UNIT_EXITED_VEHICLE" then
        if unit == "player" then
            UpdatePoints()
        end
    end
end)

**Comment by cbb356** [comment]
it is working :)
