### ISSUE TITLE
some skin related issue

### ISSUE THREAD

**Issue by solor** [Haleth/FreeUI#112]
![1](https://cloud.githubusercontent.com/assets/156806/17049855/4886b2a6-5022-11e6-9143-7acdd685ecd1.png)

![2](https://cloud.githubusercontent.com/assets/156806/17049876/6bae465e-5022-11e6-83a9-63bfcd087562.png)

![3](https://cloud.githubusercontent.com/assets/156806/17049883/72893222-5022-11e6-9410-2d157556a831.png)

![4](https://cloud.githubusercontent.com/assets/156806/17049887/78c8a26c-5022-11e6-8f54-50f5fbe4628a.png)

**Comment by solor** [comment]
https://github.com/solor/FreeUI.Fluffy/commit/f735c0038a7db45a53a177cce9d2954dc52b4a80
this should fix AchievementUI.

**Comment by solor** [comment]
https://github.com/solor/FreeUI.Fluffy/commit/605d3eb245054c1aafccbd6a4911843b1305bea6
this should fix TradeSkillUI.

**Comment by solor** [comment]
https://github.com/solor/FreeUI.Fluffy/commit/cdd827b9485cbeeb0dbf08207b1651bad1286bf0
this should fix EncounterJournalUI.

**Comment by solor** [comment]
https://github.com/solor/FreeUI.Fluffy/commit/d914497ed4341370e4a0979f45e18567b58d34e7
this should fix InspectUI.

**Comment by solor** [comment]
hope these will save your some time :rocket:

**Comment by stokbaek** [comment]
I made a new fork of FreeUI and fixed some of the issues.

It can be found here: https://github.com/stokbaek/FreeUI
