### ISSUE TITLE
Free UI Chat not worked in 7.1

### ISSUE THREAD

**Issue by cbb356** [Haleth/FreeUI#121]
After game was loaded I received next Lua error message:

Message: Interface\AddOns\FreeUI\scripts\chat.lua:19: attempt to index local 'f' (a nil value)
Time: 10/26/16 10:24:06
Count: 1
Stack: Interface\AddOns\FreeUI\scripts\chat.lua:19: in function `HideForever'
Interface\AddOns\FreeUI\scripts\chat.lua:24: in main chunk

Locals: f = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(*temporary) = "attempt to index local 'f' (a nil value)"

**Comment by Zenjaa** [comment]
workaround:

replace:  
HideForever(FriendsMicroButton)  with HideForever(QuickJoinToastButton)

comment out the following two lines: 
frame:HookScript("OnMessageScrollChanged", toggleDown)
frame:HookScript("OnShow", toggleDown)

**Comment by cbb356** [comment]
There is no Lua error now.
But chat is Blizzlike (with buttons, line below window and etc)

**Comment by Zenjaa** [comment]
I'm using this. Only thing that doesn't work in the way it's supposed to is the "toggleDown" function.

http://pastebin.com/raw/z9YgCt3Q

**Comment by cbb356** [comment]
It is working for me. Thanks.

P.S. Only you changed font for chat in your file. I changed back to C.media.font2 for me as in original FreeUI chat.lua file.

**Comment by cbb356** [comment]
in FreeUI 9.0.3 issue solved
