### ISSUE TITLE
interrupt announce doesn't work with warlock's pet

### ISSUE THREAD

**Issue by solor** [Haleth/FreeUI#61]
warlock use pet (felhunter) to interrupt spell, interrupt announce only work when interrupt by player self.

**Comment by Tamashi** [comment]
Would really like pet interrupt's to announce as well, as being a Warlock myself.

**Comment by Haleth** [comment]
eedf7e1e05962aaa8d26b382d9039859893ed665 does this work?

**Comment by Tamashi** [comment]
Can confirm it works now! Issue can be closed. Thank you so much!
