### ISSUE TITLE
limitRaidSize

### ISSUE THREAD

**Issue by solor** [Haleth/FreeUI#64]
flexible raid is up to 30 people
maximum group limit should be 6

**Comment by Haleth** [comment]
fad3d852211d1c50cae76671b8ff8023021f48bb does this work?

**Comment by solor** [comment]
New function works well, but I think "group limit" option should be preserved.
Usually there are some sub/alt characters in the raid group while we do guild raid run, so "group limit" option is still necessary.
Maybe add an option allow user to choose how many group to show would be a good idea, if it's not too much trouble ;)
