### ISSUE TITLE
GarrisonUI

### ISSUE THREAD

**Issue by solor** [Haleth/FreeUI#70]
Is that possible to make these follower slot skined?
![wowscrnshot_122314_070227](https://cloud.githubusercontent.com/assets/156806/5533281/b807b824-8a7f-11e4-8aa9-5d6e824cbc29.jpg)

**Comment by Haleth** [comment]
I'll look into this when I can be bothered at some point. The garrison UI is a mess and when you remove a follower, their textures just stay behind the follower slot, so I'd have to fix that as well.
