### ISSUE TITLE
DK rune bar

### ISSUE THREAD

**Issue by solor** [Haleth/FreeUI#74]
hard to see runes cooldown in bright environment
dark background would be better

![wowscrnshot_122914_031325](https://cloud.githubusercontent.com/assets/156806/5564741/cef335cc-8f0c-11e4-993b-a128eee00a31.jpg)

**Comment by Haleth** [comment]
c35392bd2e2b20e92bfe4fe1233d251869be0ba7 is this better?

**Comment by solor** [comment]
looks a lot better, thanks.
