### ISSUE TITLE
progress bar from objectivetrack looks misplaced

### ISSUE THREAD

**Issue by solor** [Haleth/FreeUI#75]
misplaced 2px I think
![wowscrnshot_010215_212016](https://cloud.githubusercontent.com/assets/156806/5601584/2086f226-9344-11e4-93fe-59101a6b4e9f.jpg)

**Comment by Haleth** [comment]
I'm not sure what causes this, sometimes the position is correct and sometimes it's off by 2px. I've spent a while digging through the code but I can't find anything. Running scripts in game shows that the position -should- be correct, so I've no idea why it's being rendered wrong.

My best guess is that this is the same bug that causes frame offsets in scrollframes to be wrong at times, but really, I've no idea.

**Comment by solor** [comment]
looks like it's blizzard's fault
