### ISSUE TITLE
Suggestion for dot classes

### ISSUE THREAD

**Issue by Tamashi** [Haleth/FreeUI#76]
Hey Haleth

Would it be possible to integrate some kind of DoT timer to floating nameplates, or the raid boss frames? I'm using another AddOn to do this, called Shadowed Unit Frames, but it would be awesome if you would add some kind of tracking for DoT/HoT classes.

I don't mean a simple DoT timer for your current target, but more something that keeps track of them in your UI on multiple targets, or as suggested before, above the nameplates.

**Comment by Haleth** [comment]
This is definitely on the to-do list, but it's fairly complicated to implement, especially given the limited time I have lately. I'm trying to fix a few other issues first. :)
