### ISSUE TITLE
No raid unitframes?

### ISSUE THREAD

**Issue by Tamashi** [Haleth/FreeUI#78]
Since the latest download, the raid frames seem to be missing.

Screenshot:
http://gyazo.com/f02d0173d4224dae79d18c9559d65718

**Comment by Tamashi** [comment]
Any fix? Quite annoying if you're in a Mythic raiding guild, especially if progressing on Imperator Mythic. :)

**Comment by Haleth** [comment]
b7ccdb8f79609e651ba98b3925bf0bc073fdc1d1 Ahem. Does that work?

**Comment by Tamashi** [comment]
Confirmed to be fixed, can close the issue. :)
