### ISSUE TITLE
Invasion Points counter is missing.

### ISSUE THREAD

**Issue by tbartels** [Haleth/FreeUI#81]
I may have a blindspot, but I can't find the Points counter while doing a Garrison Invasion. I've looked through the settings a few times hoping to find something related, but nothing seems to describe what I'm looking for. Is there a setting for this, or is the frame actually removed?

**Comment by myrkir** [comment]
It's between your health and your mana/rage/energy counter.

**Comment by tbartels** [comment]
Okay, thanks.
