### ISSUE TITLE
DBM issue.

### ISSUE THREAD

**Issue by mapclmao** [Haleth/FreeUI#84]
Hello, Haleth. I'm having a bit small and annoying issue. It appeared once in MoP, but, somehow, it was solved. Not i have the same problem (please, take a look at screenshot below). I have already tried to reinstall DBM, Free UI, clicked "toggle DBM" to synchronize it, deleted WTF fodlers, but nothing helps. Would be really thankful for your answer.

Best regards,
Mapclmao.
![wowscrnshot_030715_202642](https://cloud.githubusercontent.com/assets/3748359/6542730/2ce336d0-c50b-11e4-9c1a-3a8e192be364.jpg)

**Comment by solor** [comment]
Freeui has nothing to do with it, that's dbm bars default position.
Type /dbm to open dbm config panel, go to option/bar setup, then move it.

**Comment by mapclmao** [comment]
No, it has to be moved and styled automatically by Free UI like it was, without moving cooldown of upcoming boss ability to the middle. It worked correctly when I got older Free UI version. Unfortunately, I don't have any screenshot to prove what I mean. And if I move those bars in DBM options, they will restyle again. becoming larger with font that will make words laying on each other.

**Comment by solor** [comment]
That's impossible, you can check this file https://github.com/Haleth/FreeUI/blob/master/FreeUI/scripts/dbm.lua by yourself, only change bar style not position. Maybe you changed it but forget it ;)
Bars will look larger when you try move them, dont panic, just /reloadui when you done, everything gonna be ok.

**Comment by Haleth** [comment]
Did you remember to run the DBM setup in the installer (/freeui install) on each character you're using DBM on?

**Comment by mapclmao** [comment]
Yes, that's not helping. Here we are:
![wowscrnshot_031215_122220](https://cloud.githubusercontent.com/assets/3748359/6616061/baecdc24-c8b2-11e4-98f4-62c29ec4cf02.jpg)

**Comment by mapclmao** [comment]
You can close up this topoc. I started to use BigWigs, that's much more useful ^_^

Thanks for trying to help and thanks for your awesome UI.
