### ISSUE TITLE
an error in automation

### ISSUE THREAD

**Issue by rodneycheung** [Haleth/FreeUI#86]
I got an error while i was leveling my alt. it said that "QuestInfoItem1"s value is nil when i reported a mission in which i can choose gears.

201: if 
        QuestInfoItem1:IsVisible() then -- protection in case frame is closed early
        highlightFunc()
        end

so you may delete it, i think BLZ has deleted this function.

**Comment by Haleth** [comment]
Should be fixed in 1234e6980d8f91bb4d6a491707b6594ac21ea5dd, let me know if it's not. :)
