### ISSUE TITLE
Quest progress bar icon and merchant frame

### ISSUE THREAD

**Issue by solor** [Haleth/FreeUI#88]
quest progress bar icon
![](http://i.imgur.com/yLLjWnD.jpg)
![](http://i.imgur.com/lmHhuyX.jpg)

merchant frame
![](http://i.imgur.com/BAHVBrl.jpg)
![](http://i.imgur.com/ZdX3MSD.jpg)

**Comment by Haleth** [comment]
I fixed merchant frame in the latest version (actually fixed it a while ago but forgot to commit...). I know the tracker is broken, I'm working on it.
