### ISSUE TITLE
6.2.2  Update Needed.

### ISSUE THREAD

**Issue by Tamashi** [Haleth/FreeUI#95]
Since 6.2.2, the name plates don't work, and the character tab where your stats are, looks pretty weird as well. There may be more bugs, but that's what I've noticed so far.

Any plans on updating, or did you abandon? :P

**Comment by Tamashi** [comment]
Stabndard O > "Who" and "Chat" tab are broken too.

**Comment by Tamashi** [comment]
Mailbox bugged as well

**Comment by Tamashi** [comment]
Dialog text is Black

**Comment by Haleth** [comment]
a940317685f3c8ffca7e3b7d8e0fdad4a52a0dda should fix it.

**Comment by myrkir** [comment]
Updated my UI with this fix, but it only broke things even more. Am I doing it wrong?

**Comment by Haleth** [comment]
Can you try a clean install by downloading the latest version off GitHub?

**Comment by myrkir** [comment]
Cleaned out my UI folder and did a clean install and it worked, thanks a lot. :)

**Comment by Tamashi** [comment]
Haleth, the shift V health frames look Blizzard'ish. Any way to revert them back to the tiny ones?>

**Comment by Haleth** [comment]
32071ee6971fd140115ab4c09c9add3c9bbb0fda not working for you? It does for me.

**Comment by Tamashi** [comment]
Will do a clean update now (as always). Will report back.

**Comment by Tamashi** [comment]
Looks good, will close issue. Everything seems to be resolved. Wiill get back if I find anything major. Thanks a lot for your effort. I love your work.
